"""extend_file_id_length_to_50

Revision ID: e7dda82d070c
Revises: 3bdbc91b66d2
Create Date: 2025-12-31 20:15:49.260951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dda82d070c'
down_revision: Union[str, Sequence[str], None] = '3bdbc91b66d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_streams', 'file_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               comment='文件 ID（仅 file 类型，格式：UUID.扩展名）',
               existing_comment='文件 ID（仅 file 类型）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_streams', 'file_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               comment='文件 ID（仅 file 类型）',
               existing_comment='文件 ID（仅 file 类型，格式：UUID.扩展名）',
               existing_nullable=True)
    # ### end Alembic commands ###
